### PR TITLE
Update app.js

### PR DESCRIPTION
**Pull request by xushvai**
When i try 'Github repository', i debug by Safari, the bug is 'Can't find variable: $scope' on line 8.

I think just using 'else' is ok.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
So, there's 2 PR that does the same thing, and I didn't got what are you trying to fix. Could you explain a little bit?

**Comment by xushvai** [comment]
I just change 'else if ($scope.isRepo)' to 'else'

**Comment by alexandrevicenzi** [comment]
Yep, I think this code is outdated on GitHUb, I'm working on it.

If you're trying to use the master branch I thing you'll have a bad time for now.

**Comment by alexandrevicenzi** [comment]
@xushvai are you trying to use this version?

**Comment by xushvai** [comment]
Yes, i deploy it on my host, you can access http://www.gist-it.xyz

**Comment by alexandrevicenzi** [comment]
@xushvai are you using the version from NPM? because I forgot to create tags on GitHub, so there's no releases :disappointed: 

If not, I would recommend you to use from NPM. The master is a "new" Gistfy. I almost rewrite 75% and it's not ready yet.

**Comment by xushvai** [comment]
I just clone the master branch.

**Comment by alexandrevicenzi** [comment]
If you want, clone the repo again, it's up to date now.

**Comment by xushvai** [comment]
ok! Thanks for your project !

**Pull request closed without merging**
